spring:
  datasource:
    # 使用内存数据库h2，用户名、密码随意
    url: jdbc:h2:mem:test
    username: root
    password: 123456
    driver-class-name: org.h2.Driver

mybatis:
  configuration:
   map-underscore-to-camel-case: true #开启驼峰映射

